version: '3.9'

services:

  node_app:
    container_name: node_app
    build: .
    image: silver-api-compose
    working_dir: /app
    ports:
      - "3001:3001"
    environment:
      - DB_USER=${DOCKER_DB_USER}
      - DB_PASSWORD=${DOCKER_DB_PASSWORD}
      - DB_HOST=${DOCKER_DB_HOST}
      - DB_PORT=${DOCKER_DB_PORT}
      - DB_NAME=${DOCKER_DB_NAME}
      - PORT=${DOCKER_DB_PORT}
    depends_on:
      - db_api
    restart: always

  db_api:
    container_name: db-compose
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DOCKER_DB_USER}
      - POSTGRES_PASSWORD=${DOCKER_DB_PASSWORD}
      - POSTGRES_DB=${DOCKER_DB_NAME}
    volumes:
      - db-compose_data:/var/lib/postgresql/data

volumes:
  db-compose_data: {}