services:

  node-app-local:
    image: "node:18-alpine"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app/
    ports:
      - "3001:3001"
    command: ["npm", "run", "start:local"]
    env_file:
      - .env.dockercompose

    depends_on:
      - db-api-local
    restart: always

  db-api-local:
    image: postgres:14.11-alpine3.19
    ports:
      - "5432:5432"
    env_file:
      - .env.dockercompose

    volumes:
      - db-api-data-local:/var/lib/postgresql/data/

volumes:
  db-api-data-local: