version: '3.9'

services:

  node_app:
    container_name: node_app
    build: .
    image: silver-api-compose
    working_dir: /app
    ports:
      - "3001:3001"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db_api
      - DB_PORT=5432
      - DB_NAME=silver
      - PORT=3001
    depends_on:
      - db_api
    restart: always

  db_api:
    container_name: db-compose
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=silver
    volumes:
      - db-compose_data:/var/lib/postgresql/data

volumes:
  db-compose_data: {}